language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo32-7.0
  - Pharo32-6.1 
  - Pharo64-6.1
